# Small molecule force fields

# Introduction

This tutorial is to show how we usually parameterize the small molecules (such as drugs). We here will use the CGenFF and GAMESS (a QM program) to obtain all parameters.


# Methodology

The potential function (or force field) to describe the small molecules follows,

$U(r,parameters) = \sum_{bonds}K_b(b-b_0)^2 + \sum_{angles}K_{\theta}(\theta-\theta_0)^2 + \sum_{dihedrals}K_{\phi}(1+cos(n\phi-\phi_0)) $

$+ \sum_{non-bonded pairs} {\frac{q_iq_j}{4\pi\epsilon_0r_{ij}} + \epsilon_{min}^{ij}[(\frac{R_{min}^{ij}}{r_{ij}})^{12} - 2(\frac{R_{min}^{ij}}{r_{ij}})^6]}$,

The LJ parameteres for any pair can be constructed by using a Lorentz-Berthelot combination rule, 

which is
$\epsilon_{min}^{ij} = \sqrt{\epsilon_{min}^{i}\epsilon_{min}^{j}}$ and 
$R_{min}^{ij} = \frac{R_{min}^{i}+R_{min}^{j}}{2}$.

# Parameterization
```
1. Generate the atomic models consistent with the atom-type assignments by using the CGenFF

2. Optimize the geometry using QM calculations and then refine the internal structural parameters (bonds and angles)

3. Optimize the atomic partial charges using QM electrostatic potential (ESP) and also compound-water intereactions determined by the QM calculations

4. Identify "soft dihedrals",  (i.e., those with low energy barriers that are most likely to undergo conformational change), and then iteratively refines the associated dihedral parameters on the basis of QM data. 
```
**Reference**

[1]. Optimized Lennard-Jones Parameters for Druglike Small Molecules. Link: https://pubs.acs.org/doi/full/10.1021/acs.jctc.8b00172

## load a structure file with corrected atom types


In [13]:
# cd the work folder

%cd '/home/ping/tutorial/cgenff'

%cat 'ns11.xyz'

# this xyz structure file can be also created by OpenBabel, please see below.

/home/ping/tutorial/cgenff
16
 generated by VMD
 C           -1.1736822797  -1.2066086008  -0.0301408419
 H            -0.6095159838  -2.1303733524  -0.0513877284
 C            -0.4566785994   0.0020078297  -0.0006573247
 C            -1.1749611176   1.2096482446   0.0402441130
 H            -0.6129398732   2.1342399107   0.0818048197
 C            -2.5690765506   1.2061970445   0.0258811381
 H            -3.1086060729   2.1473662892   0.0272760210
 C            -3.2752836507  -0.0001391436  -0.0008124039
 H            -4.3592469939  -0.0013048772   0.0042906184
 C            -2.5673712811  -1.2055515471  -0.0224059537
 H            -3.1045210598  -2.1476130842  -0.0487116636
 C             1.0018406621   0.0001169327  -0.0154272379
 N             1.7541789270   1.1192064641  -0.1167502658
 N             3.0276237356   0.6718412343  -0.0599311380
 N             3.0244712816  -0.6773785922   0.0697049276
 N            1.7492117547  -1.1212591080   0.0982710579



## Use OpenBabel to create the mol2 file

Online tool: http://www.cheminfo.org/Chemistry/Cheminformatics/FormatConverter/index.html

mol2: topology generation for CGenFF


In [14]:
%cat ns11.mol2

@<TRIPOS>MOLECULE
NS11
 16 17 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1 C           1.3638   -0.2105   -0.2122 C.ar    1  NS11       -0.0464
      2 H           2.4293   -0.3840   -0.3509 H       1  NS11        0.0626
      3 C           0.8706    1.0991   -0.1426 C.ar    1  NS11        0.0762
      4 C          -0.5017    1.3124    0.0402 C.ar    1  NS11       -0.0464
      5 H          -0.8924    2.3264    0.0969 H       1  NS11        0.0626
      6 C          -1.3729    0.2254    0.1412 C.ar    1  NS11       -0.0609
      7 H          -2.4367    0.3994    0.2755 H       1  NS11        0.0618
      8 C          -0.8770   -1.0768    0.0646 C.ar    1  NS11       -0.0617
      9 H          -1.5562   -1.9212    0.1379 H       1  NS11        0.0618
     10 C           0.4903   -1.2948   -0.1085 C.ar    1  NS11       -0.0609
     11 H           0.8804   -2.3068   -0.1675 H       1  NS11        0.0618
     12 C           1.8130    2.2757   -0.2764 C.2     1  NS11        0.4264
     13 N

## CGenFF tool (for CHARMM)

CGenFF: https://cgenff.umaryland.edu/initguess/

To use it, you have to register and have an account.

goal: mol2 --> str (including topology and parameter files)


In [15]:
%cat ns11.str

# in this str file, it defines the topology of NS11 residue, and also provides the charges, bonds, angles, etc.
# L-J parameters can be found in the original cgenff parameter file based on the atom type provided in this str file.


* Toppar stream file generated by
* CHARMM General Force Field (CGenFF) program version 2.5
* For use with CGenFF version 4.6
*

read rtf card append
* Topologies generated by
* CHARMM General Force Field (CGenFF) program version 2.5
*
36 1

! "penalty" is the highest penalty score of the associated parameters.
! Penalties lower than 10 indicate the analogy is fair; penalties between 10
! and 50 mean some basic validation is recommended; penalties higher than
! 50 indicate poor analogy and mandate extensive validation/optimization.

RESI NS11           0.000 ! param penalty= 332.000 ; charge penalty= 242.306
GROUP            ! CHARGE   CH_PENALTY
ATOM C1     CG2R61 -0.119 !    0.000
ATOM H1     HGR61   0.115 !    0.000
ATOM C2     CG2R61  0.066 !    3.414
ATOM C3     CG2R61 -0.119 !    0.000
ATOM H2     HGR61   0.115 !    0.000
ATOM C4     CG2R61 -0.117 !    0.000
ATOM H3     HGR61   0.115 !    0.000
ATOM C5     CG2R61 -0.115 !    0.000
ATOM H4     HGR61   0.115 !    0.000
ATOM C6     

## CHARMM to Gromacs format

Please run the following command to obtain the topologies and parameters files for Gromacs simulations.

```python
python cgenff_charmm2gmx_py3_nx2.py NS11 ns11.mol2 ns11.str ~/pikes_home/work/ffs/charmm36-feb2021.ff
```

then, you will see four files to generate,

ns11_ini.pdb

ns11.prm

ns11.top

ns11.itp

Now, it is ready to run the simulations, but sometimes, you are not satisfied with these parameters generated by the CGenFF program, then
you can use the QM calculations to create the new parameters.


## Refine the parameteres using GAMESS

Initially, we can use the OpenBabel to creat the GAMESS coordinate inputs, and
use the "Basis Set Exchange (Link: https://www.basissetexchange.org/ )" to generate the basis sets.

Geometry optimization: B3LYP/6-31G**.

Energy calculations: B3LYP/6-31G**, we usually use higher level DFT method or basis set to obtain more accurate energies.

**Reference**

[1]. sobereva.com/441

[2]. GAMESS: https://www.msg.chem.iastate.edu/gamess/

### Partial charges

The most common way to obtain the partial charges is to use the Restrained ElectroStatic Potential (RESP) method.
Here, we use the Multiwfn program to generate these partial charges.

```text
Multiwfn -> /home/zgjia/Software/Multiwfn/Multiwfn_3.7_dev_bin_Linux/Multiwfn

  ./Multiwfn

 ==>   enter then select 

 ==>   7 Population analysis

 ==>   13 Merz-Kollmann (MK) ESP fitting atomic charge
           <== because this used in CGenFF, or
       18 Restrained ElectroStatic Potential (RESP) atomic charge

 ==>   1 Start calculation!

Orinal:
RESI NS11           0.000 ! param penalty= 332.000 ; charge penalty= 242.306
GROUP            ! CHARGE   CH_PENALTY
ATOM C1     CG2R61 -0.119 !    0.000
ATOM H1     HGR61   0.115 !    0.000
ATOM C2     CG2R61  0.066 !    3.414
ATOM C3     CG2R61 -0.119 !    0.000
ATOM H2     HGR61   0.115 !    0.000
ATOM C4     CG2R61 -0.117 !    0.000
ATOM H3     HGR61   0.115 !    0.000
ATOM C5     CG2R61 -0.115 !    0.000
ATOM H4     HGR61   0.115 !    0.000
ATOM C6     CG2R61 -0.117 !    0.000
ATOM H5     HGR61   0.115 !    0.000
ATOM C7     CG2R53  0.658 !  123.240
ATOM N1     NG2R50 -0.323 !  125.399
ATOM N2     NG2D1  -0.076 !  242.306
ATOM N3     NG2R50  0.040 !  182.416
ATOM N4     NG2R50 -0.353 !  139.024


MK-ESP:
  Center      Charge
    1(C )    0.384862
    2(H )   -0.071130
    3(C )   -0.928914
    4(C )    0.383994
    5(H )   -0.069325
    6(C )   -0.293483
    7(H )    0.102253
    8(C )   -0.036998
    9(H )    0.063589
   10(C )   -0.293267
   11(H )    0.101482
   12(C )    1.191738
   13(N )   -0.535406
   14(N )   -0.232956
   15(N )   -0.228320
   16(N )   -0.538120
Sum of charges:   -1.000000
RMSE:    0.004026   RRMSE:    0.031676


RESP: 
  Center      Charge
    1(C )    0.355029
    2(H )   -0.064979
    3(C )   -0.895454
    4(C )    0.354245
    5(H )   -0.063187
    6(C )   -0.267857
    7(H )    0.097482
    8(C )   -0.061257
    9(H )    0.068057
   10(C )   -0.267532
   11(H )    0.096671
   12(C )    1.179961
   13(N )   -0.533919
   14(N )   -0.232636
   15(N )   -0.228085
   16(N )   -0.536540
Sum of charges:   -1.000000
RMSE:    0.004026   RRMSE:    0.031682
```

**Reference**

[1]. J. Phys. Chem., 97, 10269 (1993). 
A well-behaved electrostatic potential based method using charge restraints for deriving atomic charges: the RESP model

[2]. Lu, Tian, and Feiwu Chen. "Multiwfn: a multifunctional wavefunction analyzer." Journal of computational chemistry 33.5 (2012): 580-592.

### L-J parameters

It often will not change these parameters, but it sometimes requires the changes, please refer to the following reference.

**Refenerce**

[1]. https://pubs.acs.org/doi/full/10.1021/acs.jctc.8b00172. Optimized Lennard-Jones Parameters for Druglike Small Molecules


### Bonded parameters

It could be determined by the optimized geometry, and also by the B3LYP or MP2 energies, where some torsion profiles could require higher-level QM calculations, to determine whether it has a high energy barrier.


# Appendix

## list all files

In [21]:
%ls '/home/ping/tutorial/cgenff'
# charmm36-feb2021.ff is the CHARMM36m force field for Gromacs

cgenff_charmm2gmx_py3_nx2.py  ns11_ini.pdb  ns11.mol2  ns11.str  ns11.xyz
charmm36-feb2021.ff/          ns11.itp      ns11.prm   ns11.top
